import Head from 'next/head'
import HomePage from './homePage/homePage'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Magic Mall | HomePage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomePage/>
    </div>

  )
}

